# Validar docker compose
compose-validate:
   docker compose config
# Validar Prometheus config
prometheus-validate:
	docker run --rm \
		-v $(PWD)/prometheus:/etc/prometheus \
		--entrypoint promtool \
		prom/prometheus \
		check config /etc/prometheus/prometheus.yml

# Validar Prometheus rules
prometheus-rules:
	docker run --rm \
		-v $(PWD)/prometheus:/etc/prometheus \
		--entrypoint promtool \
		prom/prometheus \
		check rules /etc/prometheus/alert.rules.yml

# Lint YAML
lint-yaml:
	yamllint .

# Lint Dockerfiles
lint-docker:
	hadolint ./monitoring-app/alert-receiver/Dockerfile
	hadolint ./monitoring-app/node-app/Dockerfile

# Lint JS/TS
lint-js:
	npx eslint .

# Format check
format-check:
	prettier --check .

# Build containers
docker-build:
	docker compose build

# Run containers
docker-up:
	docker compose up -d --build

# Check Prometheus /metrics
check-prometheus:
	curl -f http://localhost:9090/metrics

# Check Prometheus targets
check-targets:
	for i in {1..5}; do \
		TARGETS=$$(curl -s http://localhost:9090/api/v1/targets); \
		echo "$$TARGETS" | grep '"health":"up"' && exit 0; \
		echo "Targets not ready yet, retrying..."; \
		sleep 5; \
	done; \
	echo "Prometheus targets did not come up healthy"; \
	exit 1

# Check Grafana login
check-grafana:
	curl -f http://localhost:3000/login

# Target maestro: valida todo
check: compose-validate prometheus-validate prometheus-rules lint-yaml lint-docker lint-js format-check docker-build docker-up check-prometheus check-targets check-grafana
